services:
  - type: web
    name: sku-counter-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sku-counter-db
          property: connectionString
      - key: TIMEZONE
        value: Asia/Kolkata

databases:
  - name: sku-counter-db
    databaseName: sku_counter
